<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategory extends BaseJobeetCategory
{
	public function __toString(){
		return $this->getName();
	}
	
	public function getActiveJobs ($max = 10){
		$query = Doctrine_Query::Create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId())
			->limit($max);
			
		return Doctrine::getTable('JobeetJob')->getActiveJobs($query);
	}
	
	public function getSlug(){
		return Jobeet::slugfy($this->getName());
	}
	
}